name: Google Calendar Action
on:
  issues:
    types: [ opened ]
  # schedule:
    # Runs "at minute 1 past every hour" (see https://crontab.guru)
    # - cron: '1 * * * *'
jobs:
  actions-google-calendar:
    runs-on: ubuntu-latest
    steps:
    - name: Google Calendar
      uses: koconder/actions-google-calendar
      with:
        google-token: ${{ secrets.GOOGLE_TOKEN }}
        google-credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
        calendar-id: ${{ secrets.CALENDAR_ID }}
        json-path: ${{ secrets.JSON_PATH }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}